name: 🐳 Docker Build

on:
  pull_request:
    paths:
      - "apps/**"
      - "packages/**"
      - ".github/workflows/docker-build.yml"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.detect.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect service changes
        id: detect
        uses: ./.github/actions/detect-service-changes
        with:
          pr_mode: "true"

  build:
    needs: detect-changes
    if: ${{ fromJSON(needs.detect-changes.outputs.matrix).service[0] != null }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.detect-changes.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        id: build_image
        run: |
          chmod +x bin/docker
          ./bin/docker build ${{ matrix.service }}

      - name: Verify build
        run: |
          echo "Docker image built successfully!"
          docker images | grep ${{ matrix.service }}
