"""init

Revision ID: 74e9156d0365
Revises: 
Create Date: 2025-09-26 11:39:58.852327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e9156d0365'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cron_job_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cron_job_runs_job_name', 'cron_job_runs', ['job_name'])
    op.create_table('widgets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False, server_default='draft'),
    sa.Column('priority', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'])
    )
    op.create_index('ix_widgets_owner_id', 'widgets', ['owner_id'])
    op.create_index('ix_widgets_status', 'widgets', ['status'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_widgets_status', 'widgets')
    op.drop_index('ix_widgets_owner_id', 'widgets')
    op.drop_table('widgets')
    op.drop_index('ix_cron_job_runs_job_name', 'cron_job_runs')
    op.drop_table('cron_job_runs')
    op.drop_table('users')
    # ### end Alembic commands ###
