# Project configuration file
# This file contains all configurable values for the project

# TODO (amiller68): inject app name into project source code where appropriate
# Application name (used for configuring dev scripts, etc.)
app_name: generic

# Vault configuration
vault:
  # NOTE (amiller68): project id pointing to my generic vault
  #  TODO: replace with your actual project id you get from hcp
  project_id: a9087abb-c3b8-405c-b77f-f45e9bed9d09
  # App names for different environments. These must be unique in your HCP project.
  #  In order to work out of the box these should contain:
  #  - properly configured Google Client ID + Secret
  apps:
    dev: generic-dev
    # TODO (amiller68): add staging and production app names

dev_server:
  port: 8000
  debug: true