name: Lint 🧹

on:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  py-types:
    name: py-types 🐍
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      run: uv python install
        
    - name: Install dependencies
      run: |
        make install-py
        
    - name: Run types checks
      run: |
        make types-py

  ts-types:
    name: ts-types 🐦
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: true

    - name: Install dependencies
      run: make install-ts

    - name: Run types checks
      run: make types-ts