# Kamal deploy configuration for Static site service
service: generic-static

# NOTE: this must match the name you passed to the container registry module
# Container image
image: "<%= ENV['REGISTRY_NAME'] %>/generic-static"

# Deploy to these servers
servers:
  web:
    - "<%= ENV['DROPLET_IP'].strip %>"

# SSH configuration  
ssh:
  user: root
  key_data: ["<%= ENV['SSH_PRIVATE_KEY'] %>"]

# Registry configuration
registry:
  server: "<%= ENV['REGISTRY_ENDPOINT'] %>"
  username: "<%= ENV['DOCKERHUB_USERNAME'] %>"
  password:
    - DOCKERHUB_TOKEN

# Builder configuration
builder:
  dockerfile: static/Dockerfile
  context: "static"
  arch: amd64
  cache:
    type: registry

# Proxy configuration for SSL
proxy:
  ssl: true
  host: generic.krondor.org
  app_port: 8080