service: <%= ENV['PROJECT_NAME'] %>-ts-web

# NOTE (amiller68): do not change this!
# It is important that this is kept in sync with
#  the name of the service as described in the file
#  name.
# i.e. if the file name is py.yml, then the service name must be <%= ENV['PROJECT_NAME'] %>-py
# Container image using Docker Hub
image: <%= ENV['DOCKER_HUB_USERNAME'] %>/<%= ENV['PROJECT_NAME'] %>-ts-web

# Deploy to these servers
servers:
  web:
    - "<%= ENV['SERVER_IP'].strip %>"

# SSH configuration
ssh:
  user: root
  keys: ["<%= ENV['SSH_PRIVATE_KEY_FILE'] %>"]

# Registry configuration for Docker Hub
registry:
  username: <%= ENV['DOCKER_HUB_USERNAME'] %>
  password:
    - DOCKER_HUB_TOKEN

# Builder configuration
builder:
  dockerfile: ts/apps/web/Dockerfile
  context: "."
  arch: amd64
  cache:
    type: registry

# Proxy configuration for SSL
proxy:
  ssl: true
  host: ts.generic.krondor.org
  app_port: 3000
  healthcheck:
    path: /
