name: Python Tests 🐍🧪

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - "py/**"


jobs:
  quality:
    runs-on: ubuntu-latest
    
    # Service containers to run with the job
    services:
      # PostgreSQL service
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        # Health check to wait for postgres to start
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      run: uv python install
        
    - name: Install dependencies
      run: |
        bash bin/install.sh
        
    - name: Run database migrations
      run: |
        export POSTGRES_URL=postgresql://postgres:postgres@localhost:5432/test
        bash bin/migrate.sh
        
    - name: Run quality checks
      run: |
        export POSTGRES_URL=postgresql://postgres:postgres@localhost:5432/muze
        bash bin/test.sh
