name: 🏗️ Terraform Plan

on:
  pull_request:
    paths:
      - "iac/**"
      - ".github/workflows/terraform-*.yml"

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iac/envs

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Determine Environment
        id: env
        run: |
          if [[ "${{ github.base_ref }}" == "main" ]]; then
            echo "env_path=production" >> $GITHUB_OUTPUT
          else
            echo "Unsupported target branch: ${{ github.base_ref }}"
            exit 1
          fi

      - name: Terraform Init ECR
        id: init-ecr
        run: |
          cd ./ecr
          terraform init

      # TODO: if you add a new ecr repo, then this step will fail.
      # Obviously we should be able to t account for this, but for 
      # the sake of a demo / example this is fine
      - name: Terraform Plan ECR
        id: plan-ecr
        run: |
          cd ./ecr
          terraform plan -no-color
        continue-on-error: true

      - name: Terraform Init Environment
        id: init-env
        run: |
          cd ./production
          terraform init

      - name: Terraform Plan Environment
        id: plan-env
        run: |
          cd ./production
          terraform plan -no-color
        continue-on-error: true

      - name: Update Pull Request
        uses: actions/github-script@v6
        env:
          PLAN_ECR: "${{ steps.plan-ecr.outputs.stdout }}"
          PLAN_ENV: "${{ steps.plan-env.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`\n`;
            
            output += `
            ### ECR Changes
            #### Terraform Plan 📖\`${{ steps.plan-ecr.outcome }}\`
            <details><summary>Show ECR Plan</summary>
            
            \`\`\`\n
            ${process.env.PLAN_ECR}
            \`\`\`
            
            </details>\n`;

            output += `
            ### Environment Changes (${{ steps.env.outputs.env_path }})
            #### Terraform Plan 📖\`${{ steps.plan-env.outcome }}\`
            <details><summary>Show Environment Plan</summary>
            
            \`\`\`\n
            ${process.env.PLAN_ENV}
            \`\`\`
            
            </details>\n`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan-ecr.outcome == 'failure' || steps.plan-env.outcome == 'failure'
        run: exit 1
