name: Python CI 🐍

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fmt:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      run: uv python install
        
    - name: Install dependencies
      working-directory: py
      run: make install
        
    - name: Run fmt checks
      working-directory: py
      run: make fmt-check

  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      run: uv python install
        
    - name: Install dependencies
      working-directory: py
      run: make install
        
    - name: Run lint checks
      working-directory: py
      run: make lint

  types:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      run: uv python install
        
    - name: Install dependencies
      working-directory: py
      run: make install
        
    - name: Run type checks
      working-directory: py
      run: make types

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_DB: generic_py
          POSTGRES_USER: generic_user
          POSTGRES_PASSWORD: generic_pass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      run: uv python install
        
    - name: Install dependencies
      working-directory: py
      run: make install
        
    - name: Run tests
      working-directory: py
      env:
        POSTGRES_URL: postgresql://generic_user:generic_pass@localhost:5432/generic_py
      run: make test

  build:
    name: Build Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      run: uv python install
        
    - name: Install dependencies
      working-directory: py
      run: make install
        
    - name: Run build
      working-directory: py
      run: make build