name: TypeScript CI 🟦

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fmt:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        cache-dependency-path: ts/pnpm-lock.yaml

    - name: Install dependencies
      working-directory: ts
      run: make install

    - name: Run fmt checks
      working-directory: ts
      run: make fmt-check

  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        cache-dependency-path: ts/pnpm-lock.yaml

    - name: Install dependencies
      working-directory: ts
      run: make install

    - name: Run lint checks
      working-directory: ts
      run: make lint

  types:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        cache-dependency-path: ts/pnpm-lock.yaml

    - name: Install dependencies
      working-directory: ts
      run: make install

    - name: Run type checks
      working-directory: ts
      run: make types

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        cache-dependency-path: ts/pnpm-lock.yaml

    - name: Install dependencies
      working-directory: ts
      run: make install

    - name: Run tests
      working-directory: ts
      run: make test

  build:
    name: Build Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        cache-dependency-path: ts/pnpm-lock.yaml

    - name: Install dependencies
      working-directory: ts
      run: make install

    - name: Run build
      working-directory: ts
      run: make build