name: Python CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'py/**'
      - '.github/workflows/python.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'py/**'
      - '.github/workflows/python.yml'

defaults:
  run:
    working-directory: py

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "py/uv.lock"
    
    - name: Set up Python
      run: uv python install 3.12
    
    - name: Install dependencies
      run: make install
    
    - name: Check formatting
      run: make fmt-check
    
    - name: Run linter
      run: make lint
    
    - name: Type check
      run: make types
    
    - name: Run tests with coverage
      run: make test-cov
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        file: ./py/htmlcov/coverage.xml
        flags: python
        name: python-coverage

  build-docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      working-directory: py
      run: make docker-build
    
    - name: Run Docker image smoke test
      working-directory: py
      run: |
        docker run -d -p 8000:8000 --name py-app-test py-app
        sleep 5
        curl -f http://localhost:8000/health || exit 1
        docker stop py-app-test
        docker rm py-app-test